networks:
  intranet:

services:
  gateway:
    container_name: brook_mask
    image: brook-mask
    build:
      context: .
    command: run --port=8080 --dsn=/app/test.db
    networks:
      - intranet
    ports:
      - 8000:8080
